build:
  environment:
    python: "pypy3.7-7.3.4"  # Use PyPy 3.7
  dependencies:
    before:
      - python3 -m ensurepip
      - python3 -m pip install --upgrade pip
      - pip install telebot apscheduler python-telegram-bot 
    
  tests:
    override:
      - chmod +x bgmi || true  # Prevent failure if file doesn't exist
        # Set timeout to 30 minutes
      - python3 m.py
